# Crypto wallets to pay out to.
# Supported currencies: 
# ---- MAIN CHAINS ----
# btc, bch, ltc, doge
# ---- SMART CHAINS ----
# eth
# ---- STABLECOINS ----
# Ethereum: usdt, usdc, dai, ust

wallets: 
  btc: ""
  bch: ""
  ltc: ""
  eth: ""
  doge: ""
  dai: ""
  usdt: ""
  usdc: ""
  ust: ""

options:
  liquidate_eth_tokens: usdt
